//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsTracker.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VacationsTracker.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Action_Settings {
            get {
                return ResourceManager.GetString("Action_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Requests.
        /// </summary>
        internal static string All_Requests {
            get {
                return ResourceManager.GetString("All_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All_Requests_Shortcut {
            get {
                return ResourceManager.GetString("All_Requests_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VacationsTracker.Android.
        /// </summary>
        internal static string Android_App_Name {
            get {
                return ResourceManager.GetString("Android_App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login and password pair looks not correct. Please, retry them. Check current Caps Lock and input language settings.
        /// </summary>
        internal static string Auth_Error_Message {
            get {
                return ResourceManager.GetString("Auth_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Requests.
        /// </summary>
        internal static string Closed_Requests {
            get {
                return ResourceManager.GetString("Closed_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Closed_Requests_Shortcut {
            get {
                return ResourceManager.GetString("Closed_Requests_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication error. Please retry later.
        /// </summary>
        internal static string Communication_Error_Message {
            get {
                return ResourceManager.GetString("Communication_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        internal static string Home_Tab_List {
            get {
                return ResourceManager.GetString("Home_Tab_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Home_Tab_Profile {
            get {
                return ResourceManager.GetString("Home_Tab_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login and password pair is invalid.
        /// </summary>
        internal static string Invalid_Error_Message {
            get {
                return ResourceManager.GetString("Invalid_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Hint {
            get {
                return ResourceManager.GetString("Login_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Requests.
        /// </summary>
        internal static string Open_Requests {
            get {
                return ResourceManager.GetString("Open_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open_Requests_Shortcut {
            get {
                return ResourceManager.GetString("Open_Requests_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password_Hint {
            get {
                return ResourceManager.GetString("Password_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadiy Dobkin.
        /// </summary>
        internal static string Profile_Name {
            get {
                return ResourceManager.GetString("Profile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        internal static string Sign_In_Button_Text {
            get {
                return ResourceManager.GetString("Sign_In_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error during authentification. Please retry later.
        /// </summary>
        internal static string Unexpected_Error_Message {
            get {
                return ResourceManager.GetString("Unexpected_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string VacationStatus_Approved {
            get {
                return ResourceManager.GetString("VacationStatus_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string VacationStatus_Closed {
            get {
                return ResourceManager.GetString("VacationStatus_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        internal static string VacationStatus_Draft {
            get {
                return ResourceManager.GetString("VacationStatus_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InProgress.
        /// </summary>
        internal static string VacationStatus_InProgress {
            get {
                return ResourceManager.GetString("VacationStatus_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        internal static string VacationStatus_Submitted {
            get {
                return ResourceManager.GetString("VacationStatus_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptional Leave.
        /// </summary>
        internal static string VacationType_Exceptional {
            get {
                return ResourceManager.GetString("VacationType_Exceptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave without Pay.
        /// </summary>
        internal static string VacationType_LeaveWithoutPay {
            get {
                return ResourceManager.GetString("VacationType_LeaveWithoutPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime.
        /// </summary>
        internal static string VacationType_Overtime {
            get {
                return ResourceManager.GetString("VacationType_Overtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string VacationType_Regular {
            get {
                return ResourceManager.GetString("VacationType_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick days.
        /// </summary>
        internal static string VacationType_Sick {
            get {
                return ResourceManager.GetString("VacationType_Sick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string VacationType_Undefined {
            get {
                return ResourceManager.GetString("VacationType_Undefined", resourceCulture);
            }
        }
    }
}
